services:
  database:
    image: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}

  roof-mate:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - type: bind
        source: $PWD/frontend/target/scala-2.13/roof-mate-frontend-fastopt/main.js
        target: /var/www/public/main.js
      - type: bind
        source: $PWD/frontend/target/scala-2.13/roof-mate-frontend-fastopt/main.js.map
        target: /var/www/public/main.js.map
      - type: bind
        source: $PWD/frontend/src/main/resources/index.html
        target: /var/www/public/index.html
    env_file:
      - .env.local